apiVersion: v1
kind: Service
metadata:
  name: phpappnp
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: app0

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app0
spec:
  replicas: 5
  template:
    metadata:
      name: app0
      labels:
        app: app0
    spec:
      containers:
      - image: zigoprofesia/phpapache:8d39105
        name: phpapache
        env:
            - name: DB_HOST
              value: "database_host_env"
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "200Mi"
            cpu: "200m"              
  selector:
    matchLabels:
      app: app0

