apiVersion: v1
kind: Service
metadata:
  name: phpappnp
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
  selector:
    app: app0

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app0
spec:
  replicas: 2
  template:
    metadata:
      name: app0
      labels:
        app: app0
    spec:
      containers:
      - image: zigoprofesia/phpapache:8d39105
        name: phpapache
        env:
            - name: DB_HOST
              value: "database_host_env"
  selector:
    matchLabels:
      app: app0

--- 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: es7
spec:
  replicas: 3
  template:
    metadata:
      name: es7
      labels:
        app: es7
    spec:
      containers:
      - image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
        name: esdocker
        env:
          - name: ES_JAVA_OPTS
            value: "-Xms512m -Xmx512m"
          - name: discovery.seed_hosts
            value: ""
  selector:
    matchLabels:
      app: es7

--- 


apiVersion: v1
kind: Service
metadata:
  name: esnp
spec:
  type: NodePort
  ports:
  - port: 9200
    targetPort: 9200
    nodePort: 30090
  selector:
    app: es7