apiVersion: v1
kind: Service
metadata:
  name: phpappnp
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
  selector:
    app: app0

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app0
spec:
  replicas: 2
  template:
    metadata:
      name: app0
      labels:
        app: app0
    spec:
      containers:
      - image: zigoprofesia/phpapache:0e40eb1
        name: phpapache
        env:
            - name: DB_HOST
              value: "database_host_env"
  selector:
    matchLabels:
      app: app0

--- 

apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: es7
spec:
  version: 7.9.1
  nodeSets:
  - name: ns
    count: 2
    config:
      node.store.allow_mmap: false

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: special-config
data:
  ELASTICSEARCH_HOST:configmap
  ELASTICSEARCH_PORT:9200
  ELASTICSEARCH_PASSWORD:default

  